%----------------------------------------------------
%Program Kalkulator Latihan Windows Programming
%Matlab Windows Programming Teknik Aplikasi Komputer
%Oleh : Achmad Sabiqun Nugraha
%NIM  : 3.22.22.2.01
%Kelas: KE-1C
%----------------------------------------------------

clear all;
clc;
win1=figure(...
    'units','points',...
    'position',[130 150 400 300],...
    'color',[.3 .3 .4],...
    'menubar','none',...
    'resize','off',...
    'numbertitle','off',...
    'name','Latihan_Windows : Window Programming');

frame1=uicontrol('parent',win1,...
    'units','points',...
    'position',[0 0 400 150],...
    'backgroundcolor',[0.8500 0.3250 0.0980],...
    'style','frame');

label1=uicontrol('parent',win1,...
    'units','points',...
    'position',[0 260 400 25],...
    'backgroundcolor',[0.850 0.300 0],...
    'style','text',...
    'string','Kalkulator Sederhana',...
    'fontname','century gothic',...
    'fontsize',18,...
    'fontweight','bold');

label2=uicontrol('parent',win1,...
    'units','points',...
    'position',[110 230 100 15],...
    'style','text',...
    'string','Data ke 1',...
    'fontname','Verdana',...
    'fontsize',10);

label3=uicontrol('parent',win1,...
    'units','points',...
    'position',[110 200 100 15],...
    'style','text',...
    'string','Data ke 2',...
    'fontname','Verdana',...
    'fontsize',10);

label4=uicontrol('parent',win1,...
    'units','points',...
    'position',[110 170 100 15],...
    'style','text',...
    'string','Hasil Proses',...
    'fontname','Verdana',...
    'fontsize',10);

label5=uicontrol('parent',win1,...
    'units','points',...
    'position',[10 10 200 15],...
    'backgroundcolor',[0.987 0.544 0.233],...
    'style','text',...
    'string','Oleh: Achmad Sabiqun Nugraha',...
    'fontname','century gothic',...
    'fontsize',12,...
    'fontweight','bold');

edit1=uicontrol('parent',win1,...
    'units','points',...
    'position',[210 230 70 15],...
    'backgroundcolor',[1 1 1],...
    'style','edit',...
    'string',' ',...
    'fontname','Verdana',...
    'fontsize',10);

edit2=uicontrol('parent',win1,...
    'units','points',...
    'position',[210 200 70 15],...
    'backgroundcolor',[1 1 1],...
    'style','edit',...
    'string',' ',...
    'fontname','Verdana',...
    'fontsize',10);

edit3=uicontrol('parent',win1,...
    'units','points',...
    'position',[210 170 70 15],...
    'backgroundcolor',[1 1 1],...
    'style','edit',...
    'string','0',...
    'fontname','Verdana',...
    'fontsize',10);

tomtambah=uicontrol('parent',win1,...
    'units','points',...
    'position',[25 110 80 20],...
    'style','pushbutton',...
    'callback','tambah',...
    'string','Tambah',...
    'fontname','Verdana',...
    'fontsize',10);

tomkurang=uicontrol('parent',win1,...
    'units','points',...
    'position',[115 110 80 20],...
    'style','pushbutton',...
    'callback','kurang',...
    'string','Kurang',...
    'fontname','Verdana',...
    'fontsize',10);

tomkali=uicontrol('parent',win1,...
    'units','points',...
    'position',[205 110 80 20],...
    'style','pushbutton',...
    'callback','kali',...
    'string','Kali',...
    'fontname','Verdana',...
    'fontsize',10);

tombagi=uicontrol('parent',win1,...
    'units','points',...
    'position',[295 110 80 20],...
    'style','pushbutton',...
    'callback','bagi',...
    'string','Bagi',...
    'fontname','Verdana',...
    'fontsize',10);

tompecahan=uicontrol('parent',win1,...
    'units','points',...
    'position',[25 80 80 20],...
    'style','pushbutton',...
    'callback','pecahan',...
    'string','Satu Per',...
    'fontname','Verdana',...
    'fontsize',10);

tomakar=uicontrol('parent',win1,...
    'units','points',...
    'position',[115 80 80 20],...
    'style','pushbutton',...
    'callback','akar',...
    'string','Akar',...
    'fontname','Verdana',...
    'fontsize',10);

tomkuadrat=uicontrol('parent',win1,...
    'units','points',...
    'position',[205 80 80 20 ],...
    'style','pushbutton',...
    'callback','kuadrat',...
    'string','Kuadrat',...
    'fontname','Verdana',...
    'fontsize',10);

tompersen=uicontrol('parent',win1,...
    'units','points',...
    'position',[295 80 80 20],...
    'style','pushbutton',...
    'callback','persen',...
    'string','Persen',...
    'fontname','Verdana',...
    'fontsize',10);

tomsin=uicontrol('parent',win1,...
    'units','points',...
    'position',[25 50 80 20],...
    'style','pushbutton',...
    'callback','sin',...
    'string','Sin',...
    'fontname','Verdana',...
    'fontsize',10);

tomcos=uicontrol('parent',win1,...
    'units','points',...
    'position',[115 50 80 20],...
    'style','pushbutton',...
    'callback','cos',...
    'string','Cos',...
    'fontname','Verdana',...
    'fontsize',10);

tomtan=uicontrol('parent',win1,...
    'units','points',...
    'position',[205 50 80 20],...
    'style','pushbutton',...
    'callback','tan',...
    'string','Tan',...
    'fontname','Verdana',...
    'fontsize',10);

tomtutup=uicontrol('parent',win1,...
    'units','points',...
    'position',[295 20 80 20],...
    'style','pushbutton',...
    'string','Tutup',...
    'callback','close',...
    'fontname','Verdana',...
    'fontsize',10,...
    'fontweight','bold');